package com.app.locators;

public interface LandingPageLoc {
	String SIGN_IN_LABLE = "SIGN_IN_LABLE";
	String START_HERE_LABEL = "START_HERE_LABEL";

	String LANDING_PAGE_BUY_BTN = "LANDING_PAGE_BUY_BTN";
	String LANDING_PAGE_CHECKOUT_BTN = "LANDING_PAGE_CHECKOUT_BTN";
	String LANDING_PAGE_ORDER_SUMMARY_POPUP = "LANDING_PAGE_ORDER_SUMMARY_POPUP";
	String LANDING_PAGE_ORDER_SUMMARY_CONTINUE_BTN = "LANDING_PAGE_ORDER_SUMMARY_CONTINUE_BTN";
	String LANDING_PAGE_SELECT_PAYMENT_POPUP = " LANDING_PAGE_SELECT_PAYMENT_POPUP";
	String LANDING_PAGE_CREDIT_CARD_PAYMENT_OPT="LANDING_PAGE_CREDIT_CARD_PAYMENT_OPT";
	String LANDING_PAGE_CREDIT_CARD_NUMBER = "LANDING_PAGE_CREDIT_CARD_NUMBER";
	String LANDING_PAGE_CREDIT_CARD_EXPIRY_DATE = "LANDING_PAGE_CREDIT_CARD_EXPIRY_DATE";
	String LANDING_PAGE_CREDIT_CARD_CVV_NUMBER = "LANDING_PAGE_CREDIT_CARD_CVV_NUMBER";
	String LANDING_PAGE_CREDIT_PAY_NOW_BUTTON = "LANDING_PAGE_CREDIT_PAY_NOW_BUTTON";
	String LANDING_PAGE_MIDTRANS_PROMO_CHECKBOX = "LANDING_PAGE_MIDTRANS_PROMO_CHECKBOX";
	String LANDING_PAGE_OTP_TEXTBOX = "LANDING_PAGE_OTP_TEXTBOX";
	String LANDING_PAGE_OTP_OK_BUTTON = "LANDING_PAGE_OTP_OK_BUTTON";
	String LANDING_PAGE_SUCCESSFUL_TRANSACTION = "LANDING_PAGE_SUCCESSFUL_TRANSACTION";
	String LANDING_PAGE_FAILED_TRANSACTION = "LANDING_PAGE_FAILED_TRANSACTION";
}
