package com.app.locators;

public interface ShoppingCartPageLoc {

String	SIGNUP_EMAIL_TXTBOX="SIGNUP_EMAIL_TXTBOX";
String	CREATE_ACCOUNT_BUTTON="CREATE_ACCOUNT_BUTTON";
String LABEL_CREATE_ACCOUNT_BUTTON="LABEL_CREATE_ACCOUNT_BUTTON";

	String SHOPPINGCART_PAGE_HEADING = "SHOPPINGCART_PAGE_HEADING";
}
