package com.app.locators;

public interface SignUpPageLoc {

String	SIGNUP_EMAIL_TXTBOX="SIGNUP_EMAIL_TXTBOX";
String	CREATE_ACCOUNT_BUTTON="CREATE_ACCOUNT_BUTTON";
String LABEL_CREATE_ACCOUNT_BUTTON="LABEL_CREATE_ACCOUNT_BUTTON";
}
